### ISSUE TITLE
clang: error: the clang compiler does not support 'faltivec

### ISSUE THREAD

**Issue by st203** [aelmiger/chessboard2fen#4]
This is the issue I get after running pip install -r requirements.txt inside a virtualenv environment on Mac M1. Any ideas? Nice project btw!

clang: numpy/core/src/multiarray/alloc.c
            clang: numpy/core/src/multiarray/array_assign_scalar.c
            clang: numpy/core/src/multiarray/buffer.c
            clang: numpy/core/src/multiarray/common.c
            clang: numpy/core/src/multiarray/conversion_utils.c
            clang: numpy/core/src/multiarray/descriptor.c
            clang: numpy/core/src/multiarray/datetime_strings.c
            clang: build/src.macosx-13-arm64-3.11/numpy/core/src/multiarray/einsum.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/multiarray/hashdescr.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: build/src.macosx-13-arm64-3.11/numpy/core/src/multiarray/lowlevel_strided_loops.c

**Comment by aelmiger** [comment]
This seems like an issue with numpy on your Mac. Perhaps you can try to install a more recent version of numpy than the one listed in the requirements.txt.
